[package]
name = "app_bridge"
version = "0.5.0"
edition = "2021"
authors = ["Alexander Ross <ross@standout.se>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.7.1" }
anyhow = "1.0.95"
wasmtime = "29.0.1"
wasmtime-wasi = "29.0.1"
wasmtime-cli = "29.0.1"
wasmtime-component-util = "29.0.1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
