name: Publish Gem to RubyGems
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build the gem
        run: gem build *.gemspec

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
        run: |
          gem push *.gem
