name: Publish Gem to RubyGems
on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  ci-data:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.fetch.outputs.result }}
    steps:
      - uses: oxidize-rb/actions/fetch-ci-data@v1
        id: fetch
        with:
          supported-ruby-platforms: |
            exclude: [arm-linux, x86_64-linux-musl, aarch64-linux-musl, x64-mingw32, x64-mingw-ucrt]
          stable-ruby-versions: |
            exclude: [head]

  cross-gem:
    name: Compile native gem for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    needs: ci-data
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.ci-data.outputs.result).supported-ruby-platforms }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Install OpenSSL dependency
        run: sudo apt-get update -qq && sudo apt-get install -y -qq libssl-dev pkg-config

      - uses: oxidize-rb/actions/cross-gem@v1.4.0
        id: cross-gem
        with:
          platform: ${{ matrix.platform }}
          ruby-versions: ${{ join(fromJSON(needs.ci-data.outputs.result).stable-ruby-versions, ',') }}

      - uses: actions/upload-artifact@v4.6.1
        with:
          name: cross-gem-${{ matrix.platform }}
          path: ${{ steps.cross-gem.outputs.gem-path }}

  publish:
    name: Publish to RubyGems
    runs-on: ubuntu-latest
    needs: cross-gem
    steps:
      - name: Download built gems
        uses: actions/download-artifact@v4
        with:
          name: cross-gem-*
          path: pkg

      - name: Push to RubyGems
        env:
          GEM_HOST_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
        run: |
          for gem in pkg/*.gem; do
            gem push "$gem"
          done
