name: Publish Gem to RubyGems
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-linux, aarch64-linux, x86_64-darwin, arm64-darwin]

    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cross (for Linux)
        run: cargo install cross

      - name: Build for ${{ matrix.target }}
        run: |
          export RB_SYS_TARGET=${{ matrix.target }}
          rake build
          mv pkg/*.gem pkg/${{ matrix.target }}.gem

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gems
          path: pkg/*.gem

  push:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Download built gems
        uses: actions/download-artifact@v4
        with:
          name: gems
          path: pkg

      - name: Push to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          for gem in pkg/*.gem; do
            gem push "$gem"
          done
